version: 2.1

workflows:
  test-env-vars:
    jobs:
      - my_job

jobs:
  my_job:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: return 1
      - run: 
          name: on error
          command: echo "Hello error"
  
         
